### ISSUE TITLE
Detail Example For The *MD

### ISSUE THREAD

**Issue by Ander456** [meteorlxy/vuepress-theme-meteorlxy#1]
First of all , thank you open this repo . Can you show the ex of the content of one blog's content format ? cause i do not know how to write one ..

**Comment by meteorlxy** [comment]
@Ander456 

You can take [my own blog](https://github.com/meteorlxy/meteorlxy.github.io) as an example. 

I'll try to complete docs after upgrade to `vuepress 1.x`.

> Note that current version of my theme is for `vuepress 0.x` 😄

**Comment by Ander456** [comment]
wow. thank you again . help me lot

**Comment by Ander456** [comment]
one more question. when i build the docs-project. Then i get distribution folder but the result is not okay when i open the index.html..

**Comment by meteorlxy** [comment]
@Ander456 

You should try to serve those files in dist folder via a http server, instead of opening them directly.

For example:

```sh
npm install -g anywhere
cd ./dist
anywhere
```

**Comment by Ander456** [comment]
wow.. my mistake. the problem has been resolved. thank you again. bro

**Comment by meteorlxy** [comment]
Close as the [documentation](https://vuepress-theme-meteorlxy.meteorlxy.cn/) of the theme is available now.
