### ISSUE TITLE
加一个wechat好吗，brother

### ISSUE THREAD

**Issue by chavesgu** [meteorlxy/vuepress-theme-meteorlxy#14]

**Comment by meteorlxy** [comment]
你是说在 personalInfo 里面？

**Comment by chavesgu** [comment]
> 你是说在 personalInfo 里面？

i want to add your wechat  or other chui niu bi 的 tools

**Comment by meteorlxy** [comment]
…… 😅 这个可以发邮件问，不要开issue哈

**Comment by chavesgu** [comment]
> …… 😅 这个可以发邮件问，不要开issue哈

我发你邮箱的   没见回复。。

**Comment by meteorlxy** [comment]
邮箱客户端最近总crash，头疼

**Comment by chavesgu** [comment]
> 邮箱客户端最近总crash，头疼

用gmail装b是有代价的 😄

**Comment by chavesgu** [comment]
> 邮箱客户端最近总crash，头疼

快给联系方式 我要去你那儿学东西了
