### ISSUE TITLE
怎么设置特定页面的自定义布局

### ISSUE THREAD

**Issue by Mintnoii** [meteorlxy/vuepress-theme-meteorlxy#16]
在自定义的页面内添加了layout: SpecialLayout，
新建了.vuepress/components/SpecialLayout.vue组件，并提供了name属性，但还是会报错。

**Comment by meteorlxy** [comment]
提供一下报错内容？

**Comment by Mintnoii** [comment]
Unknown custom element: <Home> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <TheMain> at node_modules/_vuepress-theme-meteorlxy@1.0.0-alpha.22@vuepress-theme-meteorlxy/lib/components/TheMain.vue
       <ThemeMeteorlxy> at node_modules/_vuepress-theme-meteorlxy@1.0.0-alpha.22@vuepress-theme-meteorlxy/lib/layouts/GlobalLayout.vue

**Comment by meteorlxy** [comment]
这里的话一般会显示 `Unknown custom element: <SpecialLayout>`，但是你这个也没有显示出来。最好提供一个 reproduction repo

**Comment by meteorlxy** [comment]
emmm我大概知道了，这个估计 vuepress 1.x 的默认主题也挂了你可以试一试。

我在我的主题可以修一下

**Comment by meteorlxy** [comment]
@W-Qing 升级到 1.0.0-alpha.23 试一下

**Comment by Mintnoii** [comment]
@meteorlxy  thx，已解决。
