### ISSUE TITLE
页面加载失败返回404

### ISSUE THREAD

**Issue by kkkyan** [meteorlxy/vuepress-theme-meteorlxy#23]
博客中的一篇文章：https://blog.kkyan.cn   ---- 《100天跨考网研交换》

直接从首页是可以打开的，但是从外部链接进入就提示404：
https://blog.kkyan.cn/posts/2018/07/18/_100%E5%A4%A9%E8%B7%A8%E8%80%83%E7%BD%91%E7%A0%94%E4%BA%A4%E6%8D%A2.html

而且页面渲染出现问题，想知道可能的原因在哪里

使用的 1.0.0-alpha.28

之前使用 alpha25 版本没有问题

**Comment by meteorlxy** [comment]
你的博客应该在这个主题的基础上改了不少东西，不提供一个仓库的话没办法帮你定位具体问题。

试试引入插件 [vuepress-plugin-dehydrate](https://github.com/vuepress/vuepress-plugin-dehydrate) 应该能解决你的问题。

**Comment by kkkyan** [comment]
开发仓库因为存有文章没有开源，我稍后调一下

我发现您的博客也存在着类似的问题：
https://www.meteorlxy.cn/posts/2018/06/06/internship-of-2018.html

不过您的文章可以打开，但是渲染仍然有错误，无法进行页面跳转，我猜在route部分解析是不是有什么bug

**Comment by kkkyan** [comment]
似乎slug中带有数字会导致渲染出错

**Comment by meteorlxy** [comment]
我那个是Vuepress已知BUG，如果文章里使用了 `[[toc]]` 就会出现我那个问题，Vuepress 那边还没修

**Comment by kkkyan** [comment]
soga……十分感谢，我再看看

**Comment by meteorlxy** [comment]
你看看 Vuepress 官网现在也有这个问题 https://v1.vuepress.vuejs.org/guide/markdown.html

**Comment by kkkyan** [comment]
哈哈哈大写的尴尬 😅

**Comment by shigma** [comment]
@meteorlxy 哼，就知道黑我。要不是因为我那个更新你能用上侧边栏的目录吗？（强词夺理2333）这个问题后面我会修的。

@kkkyan 我看到你换了英文链接把问题绕过去了？如果要使用中文的话，可以先尝试用一下 vuepress-plugin-dehydrate，应该能解决大部分类似的问题。

**Comment by kkkyan** [comment]
@Shigma 我试了一下确实是中文链接的问题，哈哈以后改习惯用英文吧（又要开始纠结命名了）

**Comment by baixiaoyu2997** [comment]
@meteorlxy 中文图片也会有编译bug吗？ 我1.0.0-alpha.28版本中build静态图片时，如果图片名为中文会报错

**Comment by meteorlxy** [comment]
这类问题大部分是Vuepress本身的问题，你可以拿先默认主题试一下有没有相同问题
