### ISSUE TITLE
Flexible HeaderStyle Settings 

### ISSUE THREAD

**Issue by oovm** [meteorlxy/vuepress-theme-meteorlxy#26]
希望 header 能支持如下选项:

```js
    headerBackground: {
        useGeo: false,
        url: ['/assets/img1', '/assets/img2', '/assets/img3'],
        height: 150,
        headerTitle: false,
    },
```

1. 支持在多张图片里选择随机的一张作为 header 图片

https://github.com/meteorlxy/vuepress-theme-meteorlxy/blob/8558ad36b35d135b5ad67cdc00afecde39210626/lib/components/TheHeader.vue#L65-L70

2. 250px 太宽了, 应该提供一个可以自由调整高度的选项

3. 高度调小以后没地方给 HeaderTitle 了, 我找不到在哪能隐藏这个.

![image](https://user-images.githubusercontent.com/17541209/54671449-ea202780-4b30-11e9-80b6-035c32d14d3d.png)

**Comment by meteorlxy** [comment]
1. 准备添加支持不同页面不同 header，这个特性也考虑加入，谢谢提出。

2. 高度其实在 `palette.styl` 里面通过 `$bannerHeight` 可以修改，文档里忘记写了，会加上的。

3. 通过 `$bannerHeight` 修改高度后，title 应该还是居中的，不过也会考虑加上这个。

**Comment by oovm** [comment]
刚才的更新好像有 bug, `useGeo: true` 现在不会被覆盖了

---

哦, 我傻了, API 改了>>逃

**Comment by jeromepl** [comment]
@meteorlxy, is there a way to override the $bannerHeight without cloning the repo?
Sorry if this was already explained, I have been using google translate to try to make sense of the discussion here.

**Comment by meteorlxy** [comment]
@jeromepl

You can use Vuepress's `palette.styl` to override it
