### ISSUE TITLE
页面加载失败

### ISSUE THREAD

**Issue by dawnmarch** [meteorlxy/vuepress-theme-meteorlxy#3]
你好，首先感谢编写这么精美的主题，在使用中出现了一些问题，想咨询下。

我按照你github pages的[repo ](https://github.com/meteorlxy/meteorlxy.github.io/tree/next)进行配置，yarn dev后打开浏览器访问首页，结果显示空白，F12后，输出如下：
vue.runtime.esm.js?2b0e:601 [Vue warn]: Unknown custom element: <Layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <LayoutDistributor> at node_modules/@vuepress/core/lib/app/components/LayoutDistributor.vue
       <Root>

clone你的github pages的repo，测试也是有问题。
但是clone主题这个repo，确是OK的，不知道哪里出现了问题，能否帮忙解答下，多谢~

**Comment by meteorlxy** [comment]
@dawnmarch 

因为 meteorlxy.github.io 的 next 分支并没有启用，我的主页现在用的还是 src 分支。

目前 Vuepress 本身还有点问题，我提了几个 PR 修了一下，要等到 Vuepress 发下一个版本才能用，所以我这个主题也还没有发新版本。

**Comment by meteorlxy** [comment]
目前在 Vuepress 有两个改动还没发布：

- https://github.com/vuejs/vuepress/commit/199f18e5fef5d6fe3eeb2d711c7f07f226ba4c97
- https://github.com/vuejs/vuepress/commit/febe3a716e20f62644ea867d310e6683016d2c5a

等这两个改动发布之后， meteorlxy.github.io 的 next 分支我就会删掉，直接在 src 分支更新。

后面肯定还会有变动，因为 Vuepress 的官方 blog 插件还在更新，维护人员最近正在整个重写……博客主题作者目前基本是自己写一个 blog 插件先临时用着 😅

**Comment by dawnmarch** [comment]
了解，非常感谢~

**Comment by meteorlxy** [comment]
@dawnmarch 已更新

**Comment by dawnmarch** [comment]
@meteorlxy 好的，已经使用上了，感谢~
