### ISSUE TITLE
新建文章vssue设为ture会报错

### ISSUE THREAD

**Issue by Mintnoii** [meteorlxy/vuepress-theme-meteorlxy#31]
新添加md文件后，frontmatter里的vssue默认为true,本地运行后再点进文章页会报错
vssue.js?ffa6:1612 Error: Failed to get comments
    at VueComponent.initCommentsByIssueTitle (vssue.js:1343)
    at async VueComponent.init (vssue.js:1604)
因为获取不到评论然后会直接跳转到线上地址。
目前只能本地调试时先将vusse设为false，等文章编辑完成，push到线上之前再删掉。

**Comment by meteorlxy** [comment]
升级到主题的的最新版，然后 vssue 新增了关闭自动新建 Issue 的设置：

https://github.com/meteorlxy/vuepress-theme-meteorlxy/blob/8db91eca23a6b79e6c4d2e3337cbb8b51ebecefe/docs/.vuepress/config.js#L138

可以大概这样，判断是否为开发环境来开启或关闭，比如

```js
autoCreatIssue: process.env.NODE_ENV !== 'development'
```

**Comment by meteorlxy** [comment]
其实也可以考虑用这种方法配置开发和线上环境的两个 OAuth App

**Comment by Mintnoii** [comment]
好的👌迟钝了😄
