### ISSUE TITLE
热更新有点问题

### ISSUE THREAD

**Issue by zactony** [meteorlxy/vuepress-theme-meteorlxy#37]
```json
{
  "dependencies": {
    "vuepress": "^1.0.0-alpha.46",
    "vuepress-theme-meteorlxy": "^1.0.0-alpha.34"
  }
}
```
```
版本: 1.33.0 (user setup)
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```
上面是我本地的`npm`包的版本以及`VsCode`和浏览器、操作系统版本信息

问题：
我在`_posts`文件夹下写md文件，无法热更新。虽然我在`VsCode`的`Terminal`里看到本地构建完成，但是浏览器无法及时响应，即使我主动刷新也是无济于事。

**Comment by meteorlxy** [comment]
vuepress本身的热更新有问题，一直没完全解决，建议去vuepress仓库提交issue

**Comment by zactony** [comment]
好的，辛苦了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: meteorlxy <notifications@github.com>
发送时间: Friday, April 5, 2019 1:11:58 PM
收件人: meteorlxy/vuepress-theme-meteorlxy
抄送: ZacTony; Author
主题: Re: [meteorlxy/vuepress-theme-meteorlxy] 热更新有点问题 (#37)


vuepress本身的热更新有问题，一直没完全解决，建议去vuepress仓库提交issue

―

**Comment by lilonggogo** [comment]
当编辑config.js文件的时候，可以触发热更新。编辑其他md文件没有触发。
