### ISSUE TITLE
点击事件有问题

### ISSUE THREAD

**Issue by zpcwr** [meteorlxy/vuepress-theme-meteorlxy#38]
当在手机上浏览时，点击事件失效！

**Comment by meteorlxy** [comment]
提供一下具体描述，浏览器版本，什么点击事件

**Comment by zpcwr** [comment]
iphone7Plus sarafi IOS版本12.0, 样式类是navbar-toggler那个div的点击事件

**Comment by zpcwr** [comment]
已解决; 是样式的问题。把TheHeaderNavbar.vue里面的.navbar中的overflow hidden注释掉就可以了
