### ISSUE TITLE
Layout.vue does not exist 怎么解决

### ISSUE THREAD

**Issue by devtorich** [meteorlxy/vuepress-theme-meteorlxy#39]
请教一下🤨

**Comment by meteorlxy** [comment]
请提供一点详细信息。。

**Comment by devtorich** [comment]
https://github.com/vuejs/vuepress/issues/392 就是这个，最后你怎么解决的呢。。

**Comment by meteorlxy** [comment]
那个 issue 是 0.x 版本时候的事了，你现在用的 vuepress 和 vuepress-theme-meteorlxy 版本是什么？
