### ISSUE TITLE
首页图片异常

### ISSUE THREAD

**Issue by yuchanns** [meteorlxy/vuepress-theme-meteorlxy#4]
十分感谢你的主题，使得vuepress在blog方面更加漂亮了！
在文章里放图片的话，首页会显示图片的实际大小。导致穿出模块占据满整个页面的情况。
暂时我是把图片放到`<!-- more -->`后面解决

**Comment by meteorlxy** [comment]
好的，谢谢反馈。

一会儿修复一下发布个新版本，只准备更新 1.x 版本，0.x 版本的暂时不准备更新了。
