### ISSUE TITLE
自定义首页无法显示内容[Bug Report] 

### ISSUE THREAD

**Issue by ghost** [meteorlxy/vuepress-theme-meteorlxy#42]
## Describe the bug

创建/src/README.md文件，无法显示内容。

## Steps To Reproduce

none

## Screenshots

none

## Expected behavior

显示自定义的页面内容

## Environment (please complete the following information):

 - Theme Version: "^1.0.0-alpha.34"
 - Vuepress Version: "^1.0.0-alpha.47"
 - OS:  Windows 10
 - Browser: chrome 73

## Additional context

none

**Comment by meteorlxy** [comment]
![image](https://user-images.githubusercontent.com/18205362/56093385-b6031100-5efa-11e9-9ce0-38468370461f.png)

https://vuepress-theme-meteorlxy.meteorlxy.cn/custom-pages/

**Comment by ghost** [comment]
明白了 也就是自己实现一个自定义页面，然后把这个当做首页是吧？

**Comment by meteorlxy** [comment]
是的

**Comment by ghost** [comment]
Ok，可以了。 我把/src/README.md -> /src/home/README.md，然后把首页链接配置成/home/就ok了，Thx。

**Comment by meteorlxy** [comment]
不用，你直接把 `/src/README.md` 的 `layout` 改成自定义的就行

**Comment by ghost** [comment]
好的 感谢
