### ISSUE TITLE
[Feature Request] 创建Issues时，同时将博文内容保存到Issues

### ISSUE THREAD

**Issue by ghost** [meteorlxy/vuepress-theme-meteorlxy#43]
## What problem does the feature solve?

当收到评论的邮件提醒（通过评论创建了一个Issue，maybe...），查看Issue时，为了快速的定位到评论关联到的博文内容，以便决定是否需要紧急回复。

## Proposed solution

在frontmatter中加入一个可选项，是否保存博文内容，或者保存博文链接。

## Alternative solutions

none

## Additional context
vssue `issueContent `配置项应该可以完成这个功能，唯一需要注意的点，可能是博文的图片链接，需要替换为博文的原地址。

**Comment by meteorlxy** [comment]
Close as the author has been ghost :smile:
