### ISSUE TITLE
favicon角标配置无效

### ISSUE THREAD

**Issue by AqingCyan** [meteorlxy/vuepress-theme-meteorlxy#48]
在config.js中配置
`
head: ['link', {
    rel: 'icon',
    href: '/favicon.ico'
  }], 
`

没有出现网页的角标

**Comment by meteorlxy** [comment]
`favicon.ico` 是否放在 `.vuepress/public/favicon.ico` ?

> https://v1.vuepress.vuejs.org/guide/assets.html#public-files

**Comment by AqingCyan** [comment]
路径如下：
`my-vue/src/.vuepress/public/favicon.ico`
但没有出现角标

**Comment by meteorlxy** [comment]
你可以先用默认主题测试一下，`head` 这个配置项不是主题特定的，是 VuePress 基础能力。

如果默认主题下 OK 的话，请提供复现 repo 便于帮忙定位错误

**Comment by AqingCyan** [comment]
原主题测试也存在问题，后重启浏览器，清除缓存，问题解决，感谢答复！
