### ISSUE TITLE
Navbar on mobile devices not usable

### ISSUE THREAD

**Issue by mgh87** [meteorlxy/vuepress-theme-meteorlxy#5]
Just notices that on mobile devices your theme is not rendering the navbar properly, if the name of the home link is to long. I hope this helps improving your theme. Nice work.

(Andorid with chrome - if you need more information about the configuration just reply)

![screenshot_20190223-005459](https://user-images.githubusercontent.com/2005565/53277732-ba365d80-3705-11e9-84f4-18fff1cc419f.jpg)

**Comment by meteorlxy** [comment]
Yes it's an known issue. I didn't add scripts/styles to make the navbar responsive because I was ... lazy 😅 

Great thanks for your reporting, I'll enhance it!
