### ISSUE TITLE
[Bug Report] Menu button does not work (nothing display)

### ISSUE THREAD

**Issue by ozelotdev** [meteorlxy/vuepress-theme-meteorlxy#50]
## Describe the bug

Menu button does not work (nothing display)

## Steps To Reproduce

1. Go to https://vuepress-theme-meteorlxy.meteorlxy.cn/
2. Click on menu button

## Screenshots

<details>
<summary>show image</summary>
<img src="https://i.imgur.com/4NJBcb9.png">
</details>

## Environment (please complete the following information):

 - Theme Version: v1.0.2
 - Vuepress Version: v1.0.2
 - OS: iOS
 - Browser: safari, chrome, firefox

**Comment by meteorlxy** [comment]
Thanks for reporting.

This was reported by #38 but I didn't check that (I don't have iOS devices 😅 )
