### ISSUE TITLE
[Bug Report] 自动生成首页有点问题

### ISSUE THREAD

**Issue by Dashsoap** [meteorlxy/vuepress-theme-meteorlxy#58]
## Describe the bug

我写了两个文件夹，其中一个有 MD 文件一个没有 但是 路由进去以后报 404 无页面，且首页也无那篇文章。

## Steps To Reproduce

1. 我的NAV 写的是  { text: '日记', link: '/_posts/', exact: false },
2. 文件夹也是_posts
3. 文件夹下有一个.md文件
4. 在首页正确显示了这个.md 文件 但是在 localhost/_posts 下面显示的是 404 没有这个页面

 - Vuepress Version: [v1.x]
 - OS: [MacOS 14.3]

## Additional context
问题已解决 改成如下即可
 { text: '日记', link: '/posts/', exact: false },

**Comment by meteorlxy** [comment]
请把相关信息写完整好吗……这种 issue 看到就头疼

**Comment by Dashsoap** [comment]
不好意思，偷懒了 给您添麻烦了
