### ISSUE TITLE
[Feature Request] 侧边栏 ToC 支持高亮等

### ISSUE THREAD

**Issue by chendifan** [meteorlxy/vuepress-theme-meteorlxy#59]
1. 侧边栏 ToC 支持当前区间高亮显示，效果类似：
<img width="1290" alt="屏幕快照 2019-08-17 00 19 39" src="https://user-images.githubusercontent.com/22953986/63182378-07780400-c085-11e9-93a4-4adb120ac5b7.png">

2. footer 加入备案

well done and go on!

**Comment by meteorlxy** [comment]
Custom footer is supported since [v1.4.0](https://github.com/meteorlxy/vuepress-theme-meteorlxy/blob/master/CHANGELOG.md#140-2019-09-21) :tada:
