### ISSUE TITLE
[Bug Report] Using relative paths in markdown files will generate 404 links after build

### ISSUE THREAD

**Issue by kenberkeley** [meteorlxy/vuepress-theme-meteorlxy#62]
## Describe the bug

> A bit similar to https://github.com/vuejs/vuepress/issues/1227

As title.

## Steps To Reproduce

[This blog article page](https://kenberkeley.github.io/posts/my-it-job-hunting-experience-in-australia/) is generated by [this markdown file](https://github.com/kenberkeley/blog/blob/master/src/_posts/my-it-job-hunting-experience-in-australia/index.md) (raw file [here](https://raw.githubusercontent.com/kenberkeley/blog/master/src/_posts/my-it-job-hunting-experience-in-australia/index.md)).

If you just click all the links on the page directly, everything works fine.
However, if you right click, **Copy Link Address** and then paste it to a new tab address bar, press the **Enter** key, finally it will end up with `404 Not Found`.

Let's take the first link `前言` as an example.
**Copy Link Address**, we will have https://kenberkeley.github.io/_posts/my-it-job-hunting-experience-in-australia/0-preface/ , which SPA mode can handle properly whilst direct visits will always fail.

## Expected behavior

Should generate https://kenberkeley.github.io/posts/my-it-job-hunting-experience-in-australia/preface/ for the `前言` link, instead of the improper link with `/_posts/` and the actual filename `0-preface`.
The `permalink` defined in `前言` page is `/posts/my-it-job-hunting-experience-in-australia/preface`

## Environment (please complete the following information):

 - Theme Version: v1.5.0
 - Vuepress Version: v1.1.0
 - OS: *All*
 - Browser: *All*

**Comment by kenberkeley** [comment]
By the way, the [meta](https://vuepress-theme-meteorlxy.meteorlxy.cn/posts/2019/02/26/theme-guide-zh.html#%E6%96%87%E7%AB%A0-frontmatter) `上|下一篇` links are correct.

**Comment by meteorlxy** [comment]
Seems that it's a common issue of VuePress `permalink`.

It would be better if you could create issue/PR in vuepress repo :smile:

**Comment by meteorlxy** [comment]
This issue can be handled with [vuepress-plugin-redirect](https://vuepress.github.io/plugins/redirect).

Fixed in v1.5.1
