### ISSUE TITLE
update依据什么改变呢？

### ISSUE THREAD

**Issue by baixiaoyu2997** [meteorlxy/vuepress-theme-meteorlxy#64]
我在设置中是有设置lastUpdated:true的，但是更新文章update还是不变，需要md文件在git项目中吗？我的md文件每次都是用命令行复制过来这个项目的，然后再进行编译。

**Comment by meteorlxy** [comment]
需要在git项目中，原理是根据git提交记录来确定更新时间的。vuepress默认主题也是这样
