### ISSUE TITLE
[Feature Request] Override same-name components via theme inheritance

### ISSUE THREAD

**Issue by yuchanns** [meteorlxy/vuepress-theme-meteorlxy#65]
## What problem does the feature solve?
Make convience for user overriding same-name components

## Proposed solution

Referring to other components with an alias of `@theme` in the theme code

**Comment by meteorlxy** [comment]
最开始是这么写的，后来都改成相对路径了。

话说主题继承好用吗，用的场景多吗。。:sweat_smile:
