### ISSUE TITLE
[Bug Report] 草稿内容在分类和标签页面展现

### ISSUE THREAD

**Issue by yuchanns** [meteorlxy/vuepress-theme-meteorlxy#67]
## Describe the bug
在categories和tags页面会把草稿内容也展示出来

**Comment by kenberkeley** [comment]
按照正常逻辑，`draft: true` 的不应该被编译。
目前的实现是编译但不在页面显示：
https://github.com/meteorlxy/vuepress-theme-meteorlxy/search?q=draft&unscoped_q=draft

我的临时解决方案：开分支。。。`dev` 草稿，`master` 同步线上。。。

**Comment by kenberkeley** [comment]
Related https://github.com/meteorlxy/vuepress-theme-meteorlxy/issues/63

**Comment by meteorlxy** [comment]
是的。。

我一开始是把 draft 扔在别的文件夹里的，也可以避免被编译。

后面觉得 draft 在写的时候应该也有预览需求，放在 _posts 文件夹里面方便一点。

理想的状态是在 dev 时编译 draft ，build 时忽略 draft？

**Comment by kenberkeley** [comment]
@meteorlxy 是的。。。

**Comment by meteorlxy** [comment]
Pending for https://github.com/vuejs/vuepress/pull/2028
