### ISSUE TITLE
anchor 失效问题

### ISSUE THREAD

**Issue by chendifan** [meteorlxy/vuepress-theme-meteorlxy#68]
使用 anchor 连接进行跳转时，页面滚动位置有问题（不会精准的跳到连接中的 anchor 上），比如在地址栏输入 “http://xxx.com/posts/2019/11/15/测试文章#测试标题”，并不会跳到“测试标题”的 anchor 上，会有偏差，而且刷新的话，会回到刷新前当前页面所在的位置，anchor 完全失效。

**Comment by meteorlxy** [comment]
我这里不会复现，定位很准呀？

https://vuepress-theme-meteorlxy.meteorlxy.cn/posts/2019/02/27/theme-guide-en.html#installation

**Comment by chendifan** [comment]
我找不到那个特例了，但是“滑动后刷新，不会跳回地址栏#后面的 anchor”是必现的。。
