### ISSUE TITLE
关于点击文章分类或标签展示的一个小bug

### ISSUE THREAD

**Issue by frankbuf** [meteorlxy/vuepress-theme-meteorlxy#69]
# 分类与标签展示问题
每篇文章标题下会有日期、分类及标签展示。但是点击分类切换路由之后，展示的是所有标签。
标签亦是，展示的是所有的分类。

**Comment by meteorlxy** [comment]
目前是这样的：

- 点击分类，只展示该分类，但是可以筛选该分类下的不同标签的文章
- 点击标签，只展示该标签，但是可以筛选拥有该标签的不同分类的文章

你觉得怎样比较好呢？

**Comment by touyel** [comment]
我刚看了一下，您这个博客很像[技术胖](https://www.jspang.com)。
技术胖博文也是我上面提出的问题那样（点击博文下的分类显示的却是所有的标签）。我那套逻辑行不通，管我没仔细研究😄
 
我的想法：
 - 点击博文下的分类，只展示该分类下的所有文章（这似乎与`/posts`页面下的功能冲突了）
 - 在`nav`上添加`/categories`分类和`/tags`标签，点击显示所有的分类或标签。点至某一个分类或标签的时候，在下方显示该分类下的所有博文
- 首页只显示置顶文章或最新文章

以上纯属臆想，毕竟是个很大的工程。

**Comment by yuchanns** [comment]
> 目前是这样的：
> 
> * 点击分类，只展示该分类，但是可以筛选该分类下的不同标签的文章
> * 点击标签，只展示该标签，但是可以筛选拥有该标签的不同分类的文章
> 
> 你觉得怎样比较好呢？

点击分类，好像会显示所有的标签吧？即使该标签和分类组合下并无文章
建议加个开关，可以不展示标签。
我是修改样式把标签下的分类display:none
在分类下把标签display:none
