### ISSUE TITLE
[Bug Report] Banner is blank

### ISSUE THREAD

**Issue by nullRefErr** [meteorlxy/vuepress-theme-meteorlxy#75]
~~Hello I recently pulled the theme package from npm and followed the documentation. After running the `dev` script, the banner was empty. How can I fix this ?~~

~~Also I removed the `config.js/url`~~

**Edit**: Ah I found the issue. Changes not applied after updating the `config.js`. Stopping then running again fixed the problem.

**Comment by meteorlxy** [comment]
Known issue of vuepress itself. Hot-reload `.vuepress/config.js` is buggy
