### ISSUE TITLE
[Bug Report] build打包后社交媒体图标不显示

### ISSUE THREAD

**Issue by lanzhi-lee** [meteorlxy/vuepress-theme-meteorlxy#78]
## build打包后社交媒体图标不显示

在本地开发时，我配置了我的社交媒体信息，查看时显示正常，如图：

![image](https://user-images.githubusercontent.com/36190508/76183708-55f91580-6204-11ea-8b3c-b836b4db4ff9.png)

但是发现打包后，社交媒体图标却不见了，如图：

![image](https://user-images.githubusercontent.com/36190508/76183746-7aed8880-6204-11ea-9e45-c2e690924547.png)

我检查了两边，发现类名等没有太大区别，十分疑惑，求解

我的站点的线上地址：[链接](https://www.leezx.cn/posts/)

**Comment by meteorlxy** [comment]
我这边看是正常的啊？

**Comment by lanzhi-lee** [comment]
说实话我也很疑惑了，我前两天瞧见也是正常的，但是偶尔一刷新，就又没了
![image](https://user-images.githubusercontent.com/36190508/77131083-55c70880-6a95-11ea-9c9d-7a404d12b6dc.png)
我放弃了，就酱吧

**Comment by meteorlxy** [comment]
暂时先关闭了，如果能稳定复现的话可以新开一个 issue
