### ISSUE TITLE
[Feature Request] Img Thumbnail

### ISSUE THREAD

**Issue by captainAldi** [meteorlxy/vuepress-theme-meteorlxy#80]
## What problem does the feature solve?

The Needed Thumbnail for blog post list

## Proposed solution

add a thumbnail img for loop list in post list

## Alternative solutions

where i can edit it ? thank you

## Additional context

your theme is awesome.. it's just be more awesome if have thumbnail img in post list.. 

thank you

**Comment by meteorlxy** [comment]
Thanks for your interests, but we need more details for this feature:

- How to set the thumbnails?
- Where to display them?

Do you have any prototype images for this feature?

**Comment by captainAldi** [comment]
thanks for the response😄

so for the question: 

**how to set the thumbnail ?**

i think it will be nice if we can put in on the *.md file with the posts, just like img header etc👍

**where to display them ?**

it'll be nice if the thumbnail is in here 
![image](https://user-images.githubusercontent.com/48024406/77245094-a170e200-6c4e-11ea-8209-82ad97d6ea6b.png)
 
**do yo have any protoype ?**

well i didn't, just image that i put a squre grey color above..sorry
