### ISSUE TITLE
[Feature Request] 关于社交媒体图标被广告拦截插件屏蔽的优化点

### ISSUE THREAD

**Issue by lanzhi-lee** [meteorlxy/vuepress-theme-meteorlxy#81]
## 解决什么问题

线上偶然会出现的，社交媒体按钮被广告拦截插件屏蔽，导致无法显示的问题

## 如何判断是否出现该问题

若站点社交媒体不见了，开启浏览器的无痕模式，打开站点，查看图标是否出现

## 如何解决

1. 临时解决；关掉广告拦截插件，例如：[Adblocker for Chrome - NoAds](https://chrome.google.com/webstore/detail/adblocker-for-chrome-noad/alplpnakfeabeiebipdmaenpmbgknjce)
![image](https://user-images.githubusercontent.com/36190508/77534389-81058980-6ed3-11ea-92b9-18f620df68f6.png)
或者尝试其他可能引起该问题的插件

**2. 彻底解决，更换图标使用的类名 `.sns-link`**

## 如何复现

安装上面提到的插件，打开一个配置了社交媒体图标的显示站点

## 问题发现的思路

在线上站点使用审查元素选中原本应该图标的位置，发现被注入了一段css
![image](https://user-images.githubusercontent.com/36190508/77534821-549e3d00-6ed4-11ea-96e9-219f18de8782.png)
![image](https://user-images.githubusercontent.com/36190508/77534884-726ba200-6ed4-11ea-9f1e-a89c575c3b44.png)

复制出去，搜索，会发现我们使用的类名`.sns-link`

![image](https://user-images.githubusercontent.com/36190508/77534974-af379900-6ed4-11ea-86cc-dded89ada604.png)
解决

## 其他

简单搜索了源码，发现这个类名在个人信息卡和footer中被使用了，但是不知道还有没有其他特殊的含义，如有需要，可帮忙修改

**Comment by meteorlxy** [comment]
也不知道被哪家广告的类名误伤了，法克
