### ISSUE TITLE
[Bug Report] palette.styl设置无效,smoothScroll无效

### ISSUE THREAD

**Issue by baixiaoyu2997** [meteorlxy/vuepress-theme-meteorlxy#84]
palette.styl设置无效,smoothScroll设置无效

**Comment by meteorlxy** [comment]
请遵守 issue 模板。另外 smoothScroll 是默认主题的设置，不是所有主题的设置。

**Comment by baixiaoyu2997** [comment]
那这不是bug了，应该算是需求吧？ 能否添加关闭平滑滚动的支持，点击右边导航栏跳转滚动的太厉害了，要吐了

**Comment by meteorlxy** [comment]
那就提个 Feature Request ，描述清楚情况，养成良好的提 issue 习惯 （你猜 vue 主仓库为什么要加上那么繁琐的提 issue 流程）
