### ISSUE TITLE
[Feature Request] add smoothScroll config

### ISSUE THREAD

**Issue by baixiaoyu2997** [meteorlxy/vuepress-theme-meteorlxy#85]
## What problem does the feature solve?
请求添加平滑滚动相关配置项。页面内容太多时，平滑滚动的效果对我个人来说观感很差，而且也影响效率，不如直接跳转到锚点。
## Proposed solution

在`themeConfig`中添加`smoothScroll`项

## Alternative solutions

无

## Additional context

无

**Comment by meteorlxy** [comment]
看代码才想起来，其实加了这个配置，就是用法不太一样，而且忘记写到文档里了 😅 

```js
themeConfig: {
	plugins: {
		'smooth-scroll': false
	}
}
```

**Comment by meteorlxy** [comment]
其实几乎所有插件，都可以在 `config.js` 里面覆盖配置：

```js
module.exports = {
	plugins: {
		'smooth-scroll': false,
		'zooming': false
	}
}
```

**Comment by meteorlxy** [comment]
Supported in v1.9.0

**Comment by baixiaoyu2997** [comment]
十分感谢
