### ISSUE TITLE
[Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by chavesgu** [meteorlxy/vuepress-theme-meteorlxy#9]
i use sample config your provide but cause error above

**Comment by meteorlxy** [comment]
Could please provide a reproduction repo?

**Comment by chavesgu** [comment]
我就是用了你文档的教程。。然后就这样了

**Comment by baixiaoyu2997** [comment]
> 我就是用了你文档的教程。。然后就这样了

我之前也遇到了这个问题，你在教程中的操作是否都是在根目录的docs文件夹下？

**Comment by meteorlxy** [comment]
emmm我查查是不是我哪里写错了，你可以看一下我的博客大概是怎么配置的https://github.com/meteorlxy/meteorlxy.github.io

**Comment by chavesgu** [comment]
> > 我就是用了你文档的教程。。然后就这样了
> 
> 我之前也遇到了这个问题，你在教程中的操作是否都是在根目录的docs文件夹下？

是的。。我在根目录建了个docs目录，。。。。。

**Comment by meteorlxy** [comment]
大概率是和今天vuepress的更新有关，1.0.0-alpha.40修改了主题的API

**Comment by chavesgu** [comment]
> 大概率是和今天vuepress的更新有关，1.0.0-alpha.40修改了主题的API

我项目里用的是39的
不懂是啥原因

**Comment by meteorlxy** [comment]
@chavesgu 还有一种可能就是和vue2.6有关，目前我项目的lock文件还都是2.5.x。。我试一下装2.6

**Comment by chavesgu** [comment]
> @chavesgu 还有一种可能就是和vue2.6有关，目前我项目的lock文件还都是2.5.x。。我试一下装2.6

我曹。我的2.6的

**Comment by meteorlxy** [comment]
好像2.6也没啥问题，我还是查查我文档吧:sweat_smile:

**Comment by chavesgu** [comment]
> @chavesgu 还有一种可能就是和vue2.6有关，目前我项目的lock文件还都是2.5.x。。我试一下装2.6

**Comment by chavesgu** [comment]
另外我觉得这个主题的短板是移动端有点蛇皮

**Comment by baixiaoyu2997** [comment]
> > @chavesgu 还有一种可能就是和vue2.6有关，目前我项目的lock文件还都是2.5.x。。我试一下装2.6
> 
> 我曹。我的2.6的

docs下是否有md文件，如果有的话会出问题

**Comment by meteorlxy** [comment]
十分蛇皮，我连navbar都没做。后面再加

**Comment by chavesgu** [comment]
> 十分蛇皮，我连navbar都没做。后面再加

我刚刚看到有个国际友人已经提出质疑

**Comment by chavesgu** [comment]
> > > @chavesgu 还有一种可能就是和vue2.6有关，目前我项目的lock文件还都是2.5.x。。我试一下装2.6
> > 
> > 
> > 我曹。我的2.6的
> 
> docs下是否有md文件，如果有的话会出问题

不应该有个index.md吗

**Comment by chavesgu** [comment]
@meteorlxy 果然，删掉根目录的md文件就不报错了。。什么原因

**Comment by meteorlxy** [comment]
加一个index.md应该也可以，但是需要手动加上：

```md
---
layout: Home
---
```

**Comment by chavesgu** [comment]
> 加一个index.md应该也可以，但是需要手动加上：
> 
> ```lisp
> ---
> layout: Home
> ---
> ```

你这个主题  有首页的主题吗  就是那种首页不展示文章，到文章页才展示文章

**Comment by meteorlxy** [comment]
其实我本来是想这么做的，但是发现不知道首页还能放啥，干脆就放文章了囧

**Comment by chavesgu** [comment]
> 其实我本来是想这么做的，但是发现不知道首页还能放啥，干脆就放文章了囧

我发邮件给你的gmail了   你看看   我fork下来了  准备自己改改 加点东西  有好的建议我会提供给你

**Comment by meteorlxy** [comment]
嗯嗯好的
