### ISSUE TITLE
Add Dark Mode support [Feature Request] 

### ISSUE THREAD

**Issue by loctran016** [meteorlxy/vuepress-theme-meteorlxy#93]
## What problem does the feature solve?

Blog with dark mode supported (have dark/light mode switcher as well) is really fascinating.

## Proposed solution

A dark/light mode switcher look like this may be good:
![image](https://user-images.githubusercontent.com/64778285/93009393-bea5be00-f5aa-11ea-93ea-f4332d332366.png)

## Additional context

I've found some other blog theme plug-in which have Dark Mode:

* [vuepress-theme-ktquez](https://github.com/ktquez/vuepress-theme-ktquez)
* [vuepress-theme-ououe](https://github.com/tolking/vuepress-theme-ououe)

**Comment by meteorlxy** [comment]
Sorry for delay. Working on vuepress-next these days. New features may be supported in next major version with vuepress-next

**Comment by loctran016** [comment]
Don't mind, the new vuepress-next look good.
