### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by funcdfs** [meteorlxy/vuepress-theme-meteorlxy#95]
## Describe the bug

vuepress1.7.版本依赖包更新后
yarn run deploy 后主题报错数组越界

## Steps To Reproduce

使用 yarn upgrade-interactive --latest 更新 vuepress版本后
推送报错

![image](https://user-images.githubusercontent.com/56250171/97134337-f433ee80-1787-11eb-898a-a3c83e46a901.png)

## Expected behavior

好像是主题写的时候出现了数组越界的情况？，vuepress新版本 vue 报错，
之前用的vuepress1.6版本什么的都没事，然后更新依赖包后出现主题报错

## Environment (please complete the following information):

 - Theme Version: [^1.9.0]
 - Vuepress Version: [1.7.1]
 - OS: [Windows 10]
 - Browser: [chrome]

## Additional context

没学过vue，猜测是因为新版本数组行为审核更严谨了，所以更新后出现数组越界的报错导致无法推送至网页

解决方法就是回退vuepress版本，但是不是说明主题代码可能存在一定漏洞？希望检查一下可以适用于新版本vuepress

打扰了~

**Comment by meteorlxy** [comment]
https://github.com/vuejs/vuepress/issues/2656
